Repository KarinMeijvogel/datingapp, pull requests merged in 2020-04, with the labels that each got.

#10 Feature/profile
  index.js
  static/scripts/profilepage.js
  static/styles/profilepage.css
  views/nav.ejs
  views/profilepage.ejs
  views/succes.ejs
Labels: enhancement

#13 Feature/register
  index.js
  package-lock.json
  package.json
  static/scripts/register.js
  static/styles/login.css
  static/styles/register.css
  views/login.ejs
  views/register.ejs
Labels: enhancement

#15 Fixed matching system, user profile + moviefeature
  allUsers.json
  index.js
  package-lock.json
  package.json
  static/images/hian-oliveira-n_L_ppO4QtY-unsplash.jpg
  static/scripts/likedpage.js
  views/index.ejs
  views/likedpage.ejs
  views/profile.ejs
Labels: fix

#16 Development
  allUsers.json
  index.js
  package-lock.json
  package.json
  static/images/hian-oliveira-n_L_ppO4QtY-unsplash.jpg
  static/scripts/likedpage.js
  static/scripts/register.js
  static/styles/login.css
  static/styles/register.css
  views/index.ejs
  views/likedpage.ejs
  views/login.ejs
  views/profile.ejs
  views/register.ejs
Labels: fix, new features

#18 :ambulance: Fixed issue where user couldn't remove matches
  views/likedpage.ejs
Labels: fix

#21 Staging
  allUsers.json
  index.js
  package-lock.json
  package.json
  static/images/hian-oliveira-n_L_ppO4QtY-unsplash.jpg
  static/scripts/likedpage.js
  static/scripts/profilepage.js
  static/scripts/register.js
  static/styles/login.css
  static/styles/profilepage.css
  static/styles/register.css
  views/index.ejs
  views/likedpage.ejs
  views/login.ejs
  views/nav.ejs
  views/profile.ejs
  views/profilepage.ejs
  views/register.ejs
  views/succes.ejs
Labels: new features

#24 🚀 Staging
  .eslintrc.json
  index.js
  package-lock.json
  package.json
  static/scripts/profilepage.js
  static/scripts/register.js
  static/styles/profile.css
  static/styles/profilepage.css
  views/changeImg.ejs
  views/profile.ejs
  views/profilepage.ejs
  views/register.ejs
Labels: new features
